name: Release Drafter
uses: release-drafter/release-drafter@v5.18.1

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🛠 Changes'
    labels:
      - 'change'
      - 'dependencies'
change-template: '- $TITLE #$NUMBER (props to @$AUTHOR)'
template: |
  ## What's changed

  $CHANGES
